name: Deploy

on: [push]

jobs:
  build:

    runs-on: debian-10

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/repo/low-carbon.digital.git
            git pull origin master
